#9: Support deplyoment to Maven Central
itsallcode/junit5-system-extensions pull request #10
Opened 2018-10-25 18:09 UTC by redcatbear

Enhancements:
* #9: Support deployment to Maven Central

Bugfix:
* #9: Fixed JavaDoc

2018-10-25 18:10 UTC, redcatbear commented
@kaklakariada, please review.

2018-10-26 14:48 UTC, kaklakariada approved these changes

2018-10-26 14:48 UTC, kaklakariada commented on .classpath
>  <?xml version="1.0" encoding="UTF-8"?>
Do you want to check in .classpath and .project? This is generated by eclipse when importing a maven project.

2018-10-26 14:52 UTC, kaklakariada requested changes
Document how to configure bintray credentials and how to publish (just copy the instructions from oft).

2018-10-26 17:24 UTC, redcatbear commented on .classpath
>  <?xml version="1.0" encoding="UTF-8"?>
Removed and added to `.gitignore`.

2018-10-26 17:31 UTC, redcatbear commented
Added deployment info in `README.md`.

2018-10-26 17:31 UTC, redcatbear commented
@kaklakariada, please review again.

2018-10-27 09:37 UTC, kaklakariada approved these changes

2018-10-27 09:37 UTC, kaklakariada commented on README.md
> +1. There should be a notice saying "You have 6 unpublished item(s) for this package". Click the "Publish" link. Binaries will be available for download at [JCenter](https://jcenter.bintray.com/org/it
```suggestion
```

We have `publish=1` in the repo url in `pom.xml`, so artifacts are published automatically.

2018-10-27 17:05 UTC, merged