0.1.0
itsallcode/junit5-system-extensions pull request #2
Opened 2018-10-19 19:24 UTC by redcatbear

Features:
* #1: Support asserting System.exit(int)

2018-10-19 19:26 UTC, redcatbear commented
@kaklakariada, please review.

2018-10-20 05:25 UTC, kaklakariada requested changes

2018-10-20 05:25 UTC, kaklakariada commented on src/main/java/org/itsallcode/junit/sysextensions/ExitGuard.java
>      public void postProcessTestInstance(final Object arg0, final ExtensionContext context) throws Exception
```suggestion
    public void postProcessTestInstance(final Object testInstance, final ExtensionContext context)
```

2018-10-20 05:25 UTC, kaklakariada commented on src/test/java/TestSystemExit.java
> +import static org.itsallcode.junit.AssertExit.assertExit;
Don't leave this in the default package, move to org.itsallcode.junit.sysextensions

2018-10-20 05:25 UTC, kaklakariada commented on LICENSE.txt
> +                    GNU GENERAL PUBLIC LICENSE
There are two LICENSE files

2018-10-20 05:25 UTC, kaklakariada commented on pom.xml
> +        <junit.platform.version>1.3.1</junit.platform.version>
Properties are not used?
Dependencies seem to be managed via Eclipse Classpath, not via maven pom.xml

2018-10-20 18:33 UTC, redcatbear commented on LICENSE.txt
> +                    GNU GENERAL PUBLIC LICENSE
Removed the duplicate. I am thinking: should this module be Apache 2 instead?

2018-10-20 18:34 UTC, redcatbear commented on src/test/java/TestSystemExit.java
> +import static org.itsallcode.junit.AssertExit.assertExit;
Done.

2018-10-20 18:34 UTC, redcatbear commented on pom.xml
> +        <junit.platform.version>1.3.1</junit.platform.version>
This is really strange. Investigating...

2018-10-20 18:49 UTC, redcatbear commented
@kaklakariada, please check again.

2018-10-21 08:54 UTC, kaklakariada approved these changes

2018-10-21 08:59 UTC, merged

2018-10-21 10:47 UTC, kaklakariada commented on LICENSE.txt
> +                    GNU GENERAL PUBLIC LICENSE
No idea. Whatever you prefer.